# SPDX-FileCopyrightText: 2021 Union
#
# SPDX-License-Identifier: MPL-2.0

name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fsfe/reuse-action@v1.1
